==3166197== 32 bytes in 1 blocks are definitely lost in loss record 18 of 21
==3166197==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3166197==    by 0x187E3F: Arvore<int>::criaNo(int) (arvore.cpp:23)
==3166197==    by 0x178CC7: Arvore<int>::arvBusca(Arvore<int>**, int) (arvore.cpp:32)
==3166197==    by 0x1684E0: Arvore<int>::inicia(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:46)
==3166197==    by 0x14221A: C_A_T_C_H_T_E_S_T_2() (arvore.cpp:93)
==3166197==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3166197==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3166197==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3166197==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3166197==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3166197==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3166197==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==3166197== 
==3166197== 96 (32 direct, 64 indirect) bytes in 1 blocks are definitely lost in loss record 19 of 21
==3166197==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3166197==    by 0x187E3F: Arvore<int>::criaNo(int) (arvore.cpp:23)
==3166197==    by 0x178CC7: Arvore<int>::arvBusca(Arvore<int>**, int) (arvore.cpp:32)
==3166197==    by 0x1684E0: Arvore<int>::inicia(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:46)
==3166197==    by 0x1424F8: C_A_T_C_H_T_E_S_T_4() (arvore.cpp:103)
==3166197==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3166197==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3166197==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3166197==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3166197==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3166197==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3166197==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==3166197== 
==3166197== 256 (32 direct, 224 indirect) bytes in 1 blocks are definitely lost in loss record 20 of 21
==3166197==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3166197==    by 0x1881AF: Arvore<char>::criaNo(char) (arvore.cpp:23)
==3166197==    by 0x1792BE: Arvore<char>::arvBusca(Arvore<char>**, char) (arvore.cpp:32)
==3166197==    by 0x168A0E: Arvore<char>::inicia(std::__cxx11::list<char, std::allocator<char> >&) (arvore.cpp:46)
==3166197==    by 0x14287F: C_A_T_C_H_T_E_S_T_6() (arvore.cpp:114)
==3166197==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3166197==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3166197==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3166197==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3166197==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3166197==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3166197==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==3166197== 
==3166197== 288 (32 direct, 256 indirect) bytes in 1 blocks are definitely lost in loss record 21 of 21
==3166197==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3166197==    by 0x187E3F: Arvore<int>::criaNo(int) (arvore.cpp:23)
==3166197==    by 0x178CC7: Arvore<int>::arvBusca(Arvore<int>**, int) (arvore.cpp:32)
==3166197==    by 0x1684E0: Arvore<int>::inicia(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:46)
==3166197==    by 0x142C4A: C_A_T_C_H_T_E_S_T_8() (arvore.cpp:125)
==3166197==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3166197==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3166197==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3166197==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3166197==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3166197==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3166197==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==3166197== 
