==913482== 32 bytes in 1 blocks are definitely lost in loss record 1 of 5
==913482==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==913482==    by 0x16849E: Arvore<int>::inicia(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:39)
==913482==    by 0x142005: C_A_T_C_H_T_E_S_T_0() (arvore.cpp:97)
==913482==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==913482==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==913482==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==913482==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==913482==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==913482==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==913482==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==913482==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==913482==    by 0x16840E: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==913482== 
==913482== 32 bytes in 1 blocks are definitely lost in loss record 2 of 5
==913482==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==913482==    by 0x16849E: Arvore<int>::inicia(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:39)
==913482==    by 0x14221A: C_A_T_C_H_T_E_S_T_2() (arvore.cpp:105)
==913482==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==913482==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==913482==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==913482==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==913482==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==913482==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==913482==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==913482==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==913482==    by 0x16840E: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==913482== 
==913482== 32 bytes in 1 blocks are definitely lost in loss record 3 of 5
==913482==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==913482==    by 0x16849E: Arvore<int>::inicia(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:39)
==913482==    by 0x1424F8: C_A_T_C_H_T_E_S_T_4() (arvore.cpp:115)
==913482==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==913482==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==913482==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==913482==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==913482==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==913482==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==913482==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==913482==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==913482==    by 0x16840E: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==913482== 
==913482== 32 bytes in 1 blocks are definitely lost in loss record 4 of 5
==913482==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==913482==    by 0x168A6A: Arvore<char>::inicia(std::__cxx11::list<char, std::allocator<char> >&) (arvore.cpp:39)
==913482==    by 0x14287F: C_A_T_C_H_T_E_S_T_6() (arvore.cpp:126)
==913482==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==913482==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==913482==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==913482==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==913482==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==913482==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==913482==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==913482==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==913482==    by 0x16840E: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==913482== 
==913482== 32 bytes in 1 blocks are definitely lost in loss record 5 of 5
==913482==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==913482==    by 0x16849E: Arvore<int>::inicia(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:39)
==913482==    by 0x142C4A: C_A_T_C_H_T_E_S_T_8() (arvore.cpp:137)
==913482==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==913482==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==913482==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==913482==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==913482==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==913482==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==913482==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==913482==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==913482==    by 0x16840E: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==913482== 
