==1360296== 32 bytes in 1 blocks are definitely lost in loss record 9 of 19
==1360296==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360296==    by 0x17B10C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:103)
==1360296==    by 0x16AB95: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:181)
==1360296==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:122)
==1360296==    by 0x143465: C_A_T_C_H_T_E_S_T_14() (arvore.cpp:338)
==1360296==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360296==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360296==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360296==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360296==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==1360296==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==1360296==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==1360296== 
==1360296== 32 bytes in 1 blocks are definitely lost in loss record 10 of 19
==1360296==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360296==    by 0x17B10C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:103)
==1360296==    by 0x16AB95: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:181)
==1360296==    by 0x16ABB7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:184)
==1360296==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:122)
==1360296==    by 0x143750: C_A_T_C_H_T_E_S_T_16() (arvore.cpp:349)
==1360296==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360296==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360296==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360296==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360296==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==1360296==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==1360296== 
==1360296== 32 bytes in 1 blocks are definitely lost in loss record 11 of 19
==1360296==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360296==    by 0x17B10C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:103)
==1360296==    by 0x16AB95: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:181)
==1360296==    by 0x16ABB7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:184)
==1360296==    by 0x16ABB7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:184)
==1360296==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:122)
==1360296==    by 0x144254: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:383)
==1360296==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360296==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360296==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360296==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360296==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==1360296== 
==1360296== 32 bytes in 1 blocks are definitely lost in loss record 12 of 19
==1360296==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360296==    by 0x17B10C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:103)
==1360296==    by 0x16AB95: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:181)
==1360296==    by 0x16ABB7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:184)
==1360296==    by 0x16ABE1: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:186)
==1360296==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:122)
==1360296==    by 0x144254: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:383)
==1360296==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360296==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360296==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360296==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360296==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==1360296== 
==1360296== 32 bytes in 1 blocks are definitely lost in loss record 13 of 19
==1360296==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360296==    by 0x17B10C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:103)
==1360296==    by 0x16AB95: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:181)
==1360296==    by 0x16ABE1: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:186)
==1360296==    by 0x16ABE1: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:186)
==1360296==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:122)
==1360296==    by 0x144254: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:383)
==1360296==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360296==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360296==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360296==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360296==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==1360296== 
==1360296== 32 bytes in 1 blocks are definitely lost in loss record 14 of 19
==1360296==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360296==    by 0x17B10C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:103)
==1360296==    by 0x16AB95: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:181)
==1360296==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:122)
==1360296==    by 0x1445C6: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:398)
==1360296==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360296==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360296==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360296==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360296==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==1360296==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==1360296==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==1360296== 
==1360296== 32 bytes in 1 blocks are definitely lost in loss record 15 of 19
==1360296==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360296==    by 0x17B10C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:103)
==1360296==    by 0x16AB95: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:181)
==1360296==    by 0x16ABE1: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:186)
==1360296==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:122)
==1360296==    by 0x1445C6: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:398)
==1360296==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360296==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360296==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360296==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360296==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==1360296==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==1360296== 
==1360296== 32 bytes in 1 blocks are definitely lost in loss record 16 of 19
==1360296==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360296==    by 0x17B10C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:103)
==1360296==    by 0x16AB95: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:181)
==1360296==    by 0x16ABB7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:184)
==1360296==    by 0x16ABB7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:184)
==1360296==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:122)
==1360296==    by 0x1445C6: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:398)
==1360296==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360296==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360296==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360296==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360296==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==1360296== 
==1360296== 32 bytes in 1 blocks are definitely lost in loss record 17 of 19
==1360296==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360296==    by 0x17B10C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:103)
==1360296==    by 0x16AB95: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:181)
==1360296==    by 0x16ABB7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:184)
==1360296==    by 0x16ABE1: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:186)
==1360296==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:122)
==1360296==    by 0x1445C6: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:398)
==1360296==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360296==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360296==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360296==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360296==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==1360296== 
==1360296== 32 bytes in 1 blocks are definitely lost in loss record 18 of 19
==1360296==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360296==    by 0x17B10C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:103)
==1360296==    by 0x16AB95: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:181)
==1360296==    by 0x16ABB7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:184)
==1360296==    by 0x16ABE1: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:186)
==1360296==    by 0x16ABB7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:184)
==1360296==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:122)
==1360296==    by 0x1445C6: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:398)
==1360296==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360296==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360296==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360296==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360296== 
==1360296== 288 (32 direct, 256 indirect) bytes in 1 blocks are definitely lost in loss record 19 of 19
==1360296==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==1360296==    by 0x17B10C: Abb<int>* abb_inicia_no<int>(int) (arvore.cpp:103)
==1360296==    by 0x16AB95: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:181)
==1360296==    by 0x16ABB7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:184)
==1360296==    by 0x16ABE1: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:186)
==1360296==    by 0x16ABB7: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:184)
==1360296==    by 0x16A5CD: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:122)
==1360296==    by 0x143EAF: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:372)
==1360296==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==1360296==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==1360296==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==1360296==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==1360296== 
