==2918119== Invalid free() / delete / delete[] / realloc()
==2918119==    at 0x48399AB: free (vg_replace_malloc.c:538)
==2918119==    by 0x16AB3F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:195)
==2918119==    by 0x1445CF: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:398)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Address 0x4df9330 is 0 bytes inside a block of size 32 free'd
==2918119==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==2918119==    by 0x16AAF1: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:189)
==2918119==    by 0x16AA2A: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:174)
==2918119==    by 0x16AB2B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:194)
==2918119==    by 0x1445CF: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:398)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==  Block was alloc'd at
==2918119==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==2918119==    by 0x17B49B: Abb<int>* abb_inicia<int>(int) (arvore.cpp:86)
==2918119==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:114)
==2918119==    by 0x16ACA0: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:118)
==2918119==    by 0x16ACCA: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:120)
==2918119==    by 0x16A5C1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==2918119==    by 0x1445BA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119== 
==2918119== Mismatched free() / delete / delete []
==2918119==    at 0x48399AB: free (vg_replace_malloc.c:538)
==2918119==    by 0x16AB3F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:195)
==2918119==    by 0x1445E4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:399)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Address 0x4df9150 is 0 bytes inside a block of size 32 alloc'd
==2918119==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==2918119==    by 0x17B49B: Abb<int>* abb_inicia<int>(int) (arvore.cpp:86)
==2918119==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:114)
==2918119==    by 0x16A5C1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==2918119==    by 0x1445BA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119== 
==2918119== Invalid read of size 4
==2918119==    at 0x17B298: int abb_altura<int>(Abb<int>*) (arvore.cpp:37)
==2918119==    by 0x16AB62: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:203)
==2918119==    by 0x1445E4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:399)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Address 0x4df9168 is 24 bytes inside a block of size 32 free'd
==2918119==    at 0x48399AB: free (vg_replace_malloc.c:538)
==2918119==    by 0x16AB3F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:195)
==2918119==    by 0x1445E4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:399)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Block was alloc'd at
==2918119==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==2918119==    by 0x17B49B: Abb<int>* abb_inicia<int>(int) (arvore.cpp:86)
==2918119==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:114)
==2918119==    by 0x16A5C1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==2918119==    by 0x1445BA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119== 
==2918119== Invalid read of size 4
==2918119==    at 0x17B298: int abb_altura<int>(Abb<int>*) (arvore.cpp:37)
==2918119==    by 0x17B2E2: int abb_get_fb<int>(Abb<int>*) (arvore.cpp:45)
==2918119==    by 0x16ABA3: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:206)
==2918119==    by 0x1445E4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:399)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==  Address 0x4df9168 is 24 bytes inside a block of size 32 free'd
==2918119==    at 0x48399AB: free (vg_replace_malloc.c:538)
==2918119==    by 0x16AB3F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:195)
==2918119==    by 0x1445E4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:399)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Block was alloc'd at
==2918119==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==2918119==    by 0x17B49B: Abb<int>* abb_inicia<int>(int) (arvore.cpp:86)
==2918119==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:114)
==2918119==    by 0x16A5C1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==2918119==    by 0x1445BA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119== 
==2918119== Invalid read of size 8
==2918119==    at 0x17B254: Abb<int>* abb_no_minimo<int>(Abb<int>*) (arvore.cpp:161)
==2918119==    by 0x16AB03: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:192)
==2918119==    by 0x1445F9: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:400)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Address 0x4df9158 is 8 bytes inside a block of size 32 free'd
==2918119==    at 0x48399AB: free (vg_replace_malloc.c:538)
==2918119==    by 0x16AB3F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:195)
==2918119==    by 0x1445E4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:399)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Block was alloc'd at
==2918119==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==2918119==    by 0x17B49B: Abb<int>* abb_inicia<int>(int) (arvore.cpp:86)
==2918119==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:114)
==2918119==    by 0x16A5C1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==2918119==    by 0x1445BA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119== 
==2918119== Invalid read of size 4
==2918119==    at 0x16AB0C: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:193)
==2918119==    by 0x1445F9: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:400)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==    by 0x141F68: main (catch.hpp:17543)
==2918119==  Address 0x4df9150 is 0 bytes inside a block of size 32 free'd
==2918119==    at 0x48399AB: free (vg_replace_malloc.c:538)
==2918119==    by 0x16AB3F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:195)
==2918119==    by 0x1445E4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:399)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Block was alloc'd at
==2918119==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==2918119==    by 0x17B49B: Abb<int>* abb_inicia<int>(int) (arvore.cpp:86)
==2918119==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:114)
==2918119==    by 0x16A5C1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==2918119==    by 0x1445BA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119== 
==2918119== Invalid read of size 4
==2918119==    at 0x16AB18: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:194)
==2918119==    by 0x1445F9: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:400)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==    by 0x141F68: main (catch.hpp:17543)
==2918119==  Address 0x4df9150 is 0 bytes inside a block of size 32 free'd
==2918119==    at 0x48399AB: free (vg_replace_malloc.c:538)
==2918119==    by 0x16AB3F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:195)
==2918119==    by 0x1445E4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:399)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Block was alloc'd at
==2918119==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==2918119==    by 0x17B49B: Abb<int>* abb_inicia<int>(int) (arvore.cpp:86)
==2918119==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:114)
==2918119==    by 0x16A5C1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==2918119==    by 0x1445BA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119== 
==2918119== Invalid read of size 4
==2918119==    at 0x16AA0F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:173)
==2918119==    by 0x16AB2B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:194)
==2918119==    by 0x1445F9: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:400)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Address 0x4df9150 is 0 bytes inside a block of size 32 free'd
==2918119==    at 0x48399AB: free (vg_replace_malloc.c:538)
==2918119==    by 0x16AB3F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:195)
==2918119==    by 0x1445E4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:399)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Block was alloc'd at
==2918119==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==2918119==    by 0x17B49B: Abb<int>* abb_inicia<int>(int) (arvore.cpp:86)
==2918119==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:114)
==2918119==    by 0x16A5C1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==2918119==    by 0x1445BA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119== 
==2918119== Invalid read of size 4
==2918119==    at 0x16AA3C: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:175)
==2918119==    by 0x16AB2B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:194)
==2918119==    by 0x1445F9: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:400)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Address 0x4df9150 is 0 bytes inside a block of size 32 free'd
==2918119==    at 0x48399AB: free (vg_replace_malloc.c:538)
==2918119==    by 0x16AB3F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:195)
==2918119==    by 0x1445E4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:399)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Block was alloc'd at
==2918119==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==2918119==    by 0x17B49B: Abb<int>* abb_inicia<int>(int) (arvore.cpp:86)
==2918119==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:114)
==2918119==    by 0x16A5C1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==2918119==    by 0x1445BA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119== 
==2918119== Invalid read of size 8
==2918119==    at 0x16AA69: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:179)
==2918119==    by 0x16AB2B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:194)
==2918119==    by 0x1445F9: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:400)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Address 0x4df9158 is 8 bytes inside a block of size 32 free'd
==2918119==    at 0x48399AB: free (vg_replace_malloc.c:538)
==2918119==    by 0x16AB3F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:195)
==2918119==    by 0x1445E4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:399)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Block was alloc'd at
==2918119==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==2918119==    by 0x17B49B: Abb<int>* abb_inicia<int>(int) (arvore.cpp:86)
==2918119==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:114)
==2918119==    by 0x16A5C1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==2918119==    by 0x1445BA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119== 
==2918119== Invalid read of size 8
==2918119==    at 0x16AA83: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:180)
==2918119==    by 0x16AB2B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:194)
==2918119==    by 0x1445F9: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:400)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Address 0x4df9158 is 8 bytes inside a block of size 32 free'd
==2918119==    at 0x48399AB: free (vg_replace_malloc.c:538)
==2918119==    by 0x16AB3F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:195)
==2918119==    by 0x1445E4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:399)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Block was alloc'd at
==2918119==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==2918119==    by 0x17B49B: Abb<int>* abb_inicia<int>(int) (arvore.cpp:86)
==2918119==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:114)
==2918119==    by 0x16A5C1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==2918119==    by 0x1445BA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119== 
==2918119== Invalid read of size 8
==2918119==    at 0x16AA9A: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:180)
==2918119==    by 0x16AB2B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:194)
==2918119==    by 0x1445F9: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:400)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Address 0x4df9160 is 16 bytes inside a block of size 32 free'd
==2918119==    at 0x48399AB: free (vg_replace_malloc.c:538)
==2918119==    by 0x16AB3F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:195)
==2918119==    by 0x1445E4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:399)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Block was alloc'd at
==2918119==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==2918119==    by 0x17B49B: Abb<int>* abb_inicia<int>(int) (arvore.cpp:86)
==2918119==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:114)
==2918119==    by 0x16A5C1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==2918119==    by 0x1445BA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119== 
==2918119== Invalid free() / delete / delete[] / realloc()
==2918119==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==2918119==    by 0x16AAF1: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:189)
==2918119==    by 0x16AB2B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:194)
==2918119==    by 0x1445F9: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:400)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==  Address 0x4df9150 is 0 bytes inside a block of size 32 free'd
==2918119==    at 0x48399AB: free (vg_replace_malloc.c:538)
==2918119==    by 0x16AB3F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:195)
==2918119==    by 0x1445E4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:399)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Block was alloc'd at
==2918119==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==2918119==    by 0x17B49B: Abb<int>* abb_inicia<int>(int) (arvore.cpp:86)
==2918119==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:114)
==2918119==    by 0x16A5C1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==2918119==    by 0x1445BA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119== 
==2918119== Invalid free() / delete / delete[] / realloc()
==2918119==    at 0x48399AB: free (vg_replace_malloc.c:538)
==2918119==    by 0x16AB3F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:195)
==2918119==    by 0x1445F9: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:400)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Address 0x4df9150 is 0 bytes inside a block of size 32 free'd
==2918119==    at 0x48399AB: free (vg_replace_malloc.c:538)
==2918119==    by 0x16AB3F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:195)
==2918119==    by 0x1445E4: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:399)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Block was alloc'd at
==2918119==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==2918119==    by 0x17B49B: Abb<int>* abb_inicia<int>(int) (arvore.cpp:86)
==2918119==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:114)
==2918119==    by 0x16A5C1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==2918119==    by 0x1445BA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119== 
==2918119== Invalid free() / delete / delete[] / realloc()
==2918119==    at 0x48399AB: free (vg_replace_malloc.c:538)
==2918119==    by 0x16AB3F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:195)
==2918119==    by 0x14460E: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:401)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Address 0x4df9390 is 0 bytes inside a block of size 32 free'd
==2918119==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==2918119==    by 0x16AAF1: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:189)
==2918119==    by 0x16AA2A: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:174)
==2918119==    by 0x16AB2B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:194)
==2918119==    by 0x14460E: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:401)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==  Block was alloc'd at
==2918119==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==2918119==    by 0x17B49B: Abb<int>* abb_inicia<int>(int) (arvore.cpp:86)
==2918119==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:114)
==2918119==    by 0x16ACA0: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:118)
==2918119==    by 0x16ACCA: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:120)
==2918119==    by 0x16ACA0: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:118)
==2918119==    by 0x16A5C1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==2918119==    by 0x1445BA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119== 
==2918119== Invalid free() / delete / delete[] / realloc()
==2918119==    at 0x48399AB: free (vg_replace_malloc.c:538)
==2918119==    by 0x16AB3F: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:195)
==2918119==    by 0x144623: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:402)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==    by 0x16A4C6: int Catch::Session::run<char>(int, char const* const*) (catch.hpp:13236)
==2918119==  Address 0x4df92d0 is 0 bytes inside a block of size 32 free'd
==2918119==    at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:584)
==2918119==    by 0x16AAF1: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:189)
==2918119==    by 0x16AB2B: Abb<int>* abb_remove<int>(Abb<int>*, int) (arvore.cpp:194)
==2918119==    by 0x144623: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:402)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119==    by 0x12C050: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==2918119==    by 0x12D2C1: Catch::Session::runInternal() (catch.hpp:13562)
==2918119==    by 0x12CFF4: Catch::Session::run() (catch.hpp:13518)
==2918119==  Block was alloc'd at
==2918119==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==2918119==    by 0x17B49B: Abb<int>* abb_inicia<int>(int) (arvore.cpp:86)
==2918119==    by 0x16AC7B: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:114)
==2918119==    by 0x16ACCA: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:120)
==2918119==    by 0x16ACA0: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:118)
==2918119==    by 0x16A5C1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:104)
==2918119==    by 0x1445BA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:397)
==2918119==    by 0x130863: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==2918119==    by 0x12FBCA: Catch::TestCase::invoke() const (catch.hpp:14169)
==2918119==    by 0x12A92A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==2918119==    by 0x12A6AE: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==2918119==    by 0x129345: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==2918119== 
