==3167266== 32 bytes in 1 blocks are definitely lost in loss record 1 of 11
==3167266==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167266==    by 0x17AE98: Abb<int>* abb_inicia<int>(int) (arvore.cpp:89)
==3167266==    by 0x16AA26: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:118)
==3167266==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:108)
==3167266==    by 0x1424A2: C_A_T_C_H_T_E_S_T_4() (arvore.cpp:192)
==3167266==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167266==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167266==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167266==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167266==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167266==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167266==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167266== 
==3167266== 32 bytes in 1 blocks are definitely lost in loss record 2 of 11
==3167266==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167266==    by 0x17AE98: Abb<int>* abb_inicia<int>(int) (arvore.cpp:89)
==3167266==    by 0x16AA26: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:118)
==3167266==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:108)
==3167266==    by 0x1427E3: C_A_T_C_H_T_E_S_T_6() (arvore.cpp:203)
==3167266==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167266==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167266==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167266==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167266==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167266==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167266==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167266== 
==3167266== 32 bytes in 1 blocks are definitely lost in loss record 3 of 11
==3167266==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167266==    by 0x17AE98: Abb<int>* abb_inicia<int>(int) (arvore.cpp:89)
==3167266==    by 0x16AA26: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:118)
==3167266==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:108)
==3167266==    by 0x142B24: C_A_T_C_H_T_E_S_T_8() (arvore.cpp:214)
==3167266==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167266==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167266==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167266==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167266==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167266==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167266==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167266== 
==3167266== 32 bytes in 1 blocks are definitely lost in loss record 4 of 11
==3167266==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167266==    by 0x17AE98: Abb<int>* abb_inicia<int>(int) (arvore.cpp:89)
==3167266==    by 0x16AA26: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:118)
==3167266==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:108)
==3167266==    by 0x142E65: C_A_T_C_H_T_E_S_T_10() (arvore.cpp:225)
==3167266==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167266==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167266==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167266==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167266==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167266==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167266==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167266== 
==3167266== 32 bytes in 1 blocks are definitely lost in loss record 5 of 11
==3167266==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167266==    by 0x17AE98: Abb<int>* abb_inicia<int>(int) (arvore.cpp:89)
==3167266==    by 0x16AA26: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:118)
==3167266==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:108)
==3167266==    by 0x1431A6: C_A_T_C_H_T_E_S_T_12() (arvore.cpp:236)
==3167266==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167266==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167266==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167266==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167266==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167266==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167266==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167266== 
==3167266== 32 bytes in 1 blocks are definitely lost in loss record 6 of 11
==3167266==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167266==    by 0x17AE98: Abb<int>* abb_inicia<int>(int) (arvore.cpp:89)
==3167266==    by 0x16AA26: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:118)
==3167266==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:108)
==3167266==    by 0x143449: C_A_T_C_H_T_E_S_T_14() (arvore.cpp:245)
==3167266==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167266==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167266==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167266==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167266==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167266==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167266==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167266== 
==3167266== 32 bytes in 1 blocks are definitely lost in loss record 7 of 11
==3167266==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167266==    by 0x17AE98: Abb<int>* abb_inicia<int>(int) (arvore.cpp:89)
==3167266==    by 0x16AA26: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:118)
==3167266==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:108)
==3167266==    by 0x143734: C_A_T_C_H_T_E_S_T_16() (arvore.cpp:256)
==3167266==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167266==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167266==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167266==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167266==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167266==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167266==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167266== 
==3167266== 32 bytes in 1 blocks are definitely lost in loss record 8 of 11
==3167266==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167266==    by 0x17AE98: Abb<int>* abb_inicia<int>(int) (arvore.cpp:89)
==3167266==    by 0x16AA26: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:118)
==3167266==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:108)
==3167266==    by 0x143ADA: C_A_T_C_H_T_E_S_T_18() (arvore.cpp:268)
==3167266==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167266==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167266==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167266==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167266==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167266==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167266==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167266== 
==3167266== 32 bytes in 1 blocks are definitely lost in loss record 9 of 11
==3167266==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167266==    by 0x17AE98: Abb<int>* abb_inicia<int>(int) (arvore.cpp:89)
==3167266==    by 0x16AA26: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:118)
==3167266==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:108)
==3167266==    by 0x143E93: C_A_T_C_H_T_E_S_T_20() (arvore.cpp:279)
==3167266==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167266==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167266==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167266==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167266==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167266==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167266==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167266== 
==3167266== 32 bytes in 1 blocks are definitely lost in loss record 10 of 11
==3167266==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167266==    by 0x17AE98: Abb<int>* abb_inicia<int>(int) (arvore.cpp:89)
==3167266==    by 0x16AA26: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:118)
==3167266==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:108)
==3167266==    by 0x144238: C_A_T_C_H_T_E_S_T_22() (arvore.cpp:290)
==3167266==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167266==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167266==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167266==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167266==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167266==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167266==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167266== 
==3167266== 32 bytes in 1 blocks are definitely lost in loss record 11 of 11
==3167266==    at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==3167266==    by 0x17AE98: Abb<int>* abb_inicia<int>(int) (arvore.cpp:89)
==3167266==    by 0x16AA26: Abb<int>* abb_insere<int>(Abb<int>*, int) (arvore.cpp:118)
==3167266==    by 0x16A5B1: Abb<int>* abb_inicia<int>(std::__cxx11::list<int, std::allocator<int> >&) (arvore.cpp:108)
==3167266==    by 0x1445AA: C_A_T_C_H_T_E_S_T_24() (arvore.cpp:305)
==3167266==    by 0x130853: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:14330)
==3167266==    by 0x12FBBA: Catch::TestCase::invoke() const (catch.hpp:14169)
==3167266==    by 0x12A91A: Catch::RunContext::invokeActiveTestCase() (catch.hpp:13025)
==3167266==    by 0x12A69E: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:12998)
==3167266==    by 0x129335: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:12759)
==3167266==    by 0x12C040: Catch::(anonymous namespace)::TestGroup::execute() (catch.hpp:13352)
==3167266==    by 0x12D2B1: Catch::Session::runInternal() (catch.hpp:13562)
==3167266== 
